version: '3.1'
services:
  mariadb:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=moodle
    secrets:
      - mysql_root_password
    networks:
      - moodle_network

  moodle:
    image: bitnami/moodle:4.1.2
    ports:
      - 8080:8080
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_USER=root
      - MOODLE_DATABASE_PASSWORD_FILE=/run/secrets/moodle_database_password
      - MOODLE_DATABASE_NAME=moodle
      - PUID=998
      - PGID=100
    volumes:
      - moodledata:/bitnami/moodle
    depends_on:
      - mariadb
    secrets:
      - moodle_database_password
    networks:
      - moodle_network

networks:
  moodle_network:

volumes:
  moodledata:
  dbdata:

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt
  moodle_database_password:
    file: ./moodle_database_password.txt